baseURL = 'https://example.org/'
languageCode = 'ja-jp'
title = 'いただきます - 隔たりのない日本食文化体験を'
theme = 'ananke'

[deployment]
[[deployment.targets]]
URL = "gs://itadakimasu-docs"
[[deployment.matchers]]
# all htmls
pattern = "^.*\\.html$"
cacheControl = "no-store"
